/* Two threads sharing the same cache lines
 * Two threads sharing the same variables
 * perf command:

 * For TIGER LAKE:

sudo perf stat -e cycles:u,instructions:u,mem_inst_retired.all_loads:uP,mem_load_retired.l1_hit:uP,mem_load_retired.l1_miss:uP,mem_load_retired.l2_hit:uP,mem_load_retired.l2_miss:uP,mem_load_retired.l3_hit:uP,mem_load_retired.l3_miss:uP,mem_load_l3_hit_retired.xsnp_hit:uP,mem_load_l3_hit_retired.xsnp_hitm:uP,mem_load_l3_hit_retired.xsnp_miss:uP,mem_load_l3_hit_retired.xsnp_none:uP,l2_rqsts.rfo_hit:u,l2_rqsts.rfo_miss:u,l2_rqsts.all_rfo:u,offcore_requests.demand_rfo:u,cycle_activity.cycles_mem_any:u,cycle_activity.stalls_mem_any:u,cycle_activity.stalls_total:u   -- ./cache-line-sharing 

*/

#define _GNU_SOURCE
#include <stdio.h>
#include <pthread.h>
#include <unistd.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#define MAX_ITER 1000000000

volatile 
struct elem {
    uint64_t w1l1;
    uint64_t w2l1;
    uint64_t w3l1;
    uint64_t w4l1;
    uint64_t w5l1;
    uint64_t w6l1;
    uint64_t w7l1;
    uint64_t w8l1;

    uint64_t w1l2;
    uint64_t w2l2;
    uint64_t w3l2;
    uint64_t w4l2;
    uint64_t w5l2;
    uint64_t w6l2;
    uint64_t w7l2;
    uint64_t w8l2;
} item;

static void *thread_start1(void * arg){

    pid_t tid;
    static int counter = 0;

    tid = gettid();
    printf("Thread1 %d &counter %p &item %p\n", tid, &counter, &item);
    for (uint64_t iter = 0; iter < MAX_ITER; iter++){
        //uncomment for atomics tests
        __sync_add_and_fetch(&item.w1l1,1);
        
        //uncomment for perf c2c analysis where we rely on hitm counts being
        //generated by the CPU
        //item.w1l1 = counter++;
        
        //uncomment for simple false sharing analysis but perf c2c won't report this 
        //due to tigerlake PMU peculiarities in generating hitms
        //item.w1l1 += 1;
        asm volatile("" : : "m" (item));
    }
    return NULL;
}

static void *thread_start2(void * arg){

    pid_t tid;
    volatile static int tmp = 0;

    tid = gettid();
    printf("Thread2 %d &tmp %p\n", tid, &tmp);
    for (uint64_t iter = 0; iter < MAX_ITER; iter++){
        //uncomment for atomics tests
        __sync_add_and_fetch(&item.w2l1,1);
        
        //uncomment for perf c2c analysis where we rely on hitm counts being
        //generated by the CPU
        //tmp = item.w2l1;

        //uncomment for simple false sharing analysis but perf c2c won't report this 
        //due to tigerlake PMU peculiarities in generating hitms
        //item.w2l1 += 1;
        asm volatile("" : : "m" (item));
    }
    return NULL;
}

void main(){
    int s;
    pthread_attr_t attr;
    pthread_t th1,th2;
    cpu_set_t c;
    void *res;

    memset((void *)&item, 0, sizeof(struct elem));

    CPU_ZERO(&c);
    s = pthread_attr_init(&attr);
    if (s != 0)
        perror("pthread_attr_init");

    CPU_SET(10, &c);
    pthread_attr_setaffinity_np(&attr, sizeof(c), &c);
    s = pthread_create(&th1, &attr, thread_start1, NULL);
    if (s != 0)
        perror("pthread_create for th1"); 

    CPU_ZERO(&c);
    CPU_SET(12, &c);
    pthread_attr_setaffinity_np(&attr, sizeof(c), &c);
    s = pthread_create(&th2, &attr, thread_start2, NULL);
    if (s != 0)
        perror("pthread_create for th2");

    s = pthread_attr_destroy(&attr); 
    if (s != 0)
        perror("pthread_attr_destroy");

    s = pthread_join(th1, &res);
    if (s != 0)
        perror("pthread_join for th1");

    s = pthread_join(th2, &res);
    if (s != 0)
        perror("pthread_join for th2");
}
